version: '3'
​
volumes:
  data: 
​
networks:
  nw-net:
​
services:
  nwdb: 
    image: zeckem/northwind:af76780
    build:
      context: ./database
    volumes:
    - data:/var/lib/mysql
    networks:
    - nw-net
​
  nwapp: 
    image: zeckem/northwind_node:v1
    build:
      context: ./server
    environment:
    - DB_HOST=nwdb
    ports: 
    - 8080:3000
    networks:
    - nw-net