---
apiVersion: v1
kind: ConfigMap
metadata:
    name: wordpress-cm
    labels:
        app: wordpress

data:
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_HOST: wpdb-cluster-mysql.wordpress.svc.cluster.local
    WORDPRESS_DB_NAME: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress-app
    labels:
        app: wordpress

spec:
    replicas: 1
        
    selector:
        matchLabels:
            app: wordpress-pod

    template:
        metadata:
            name: wordpress-app-pod
            labels:
                app: wordpress-pod
        spec:
            volumes:
                - name: wp-vol
                  persistentVolumeClaim:
                    claimName: wp-pvc
            containers:
            - name: wp-container
              image: wordpress:latest
              imagePullPolicy: IfNotPresent
              env: 
              - name: WORDPRESS_DB_USER
                valueFrom:
                    configMapKeyRef:
                        name: wordpress-cm
                        key: WORDPRESS_DB_USER
              - name: WORDPRESS_DB_HOST
                valueFrom:
                    configMapKeyRef:
                        name: wordpress-cm
                        key: WORDPRESS_DB_HOST
              - name: WORDPRESS_DB_PASSWORD
                valueFrom:  
                    secretKeyRef:  
                        name: wpdb-cluster-secret
                        key: ROOT_PASSWORD
              ports:
              - name: wp-port
                  containerPort: 80
              
              volumeMounts:
              - name: wp-vol
                  mountPath: /var/www/html

---
apiVersion: v1
kind: Service
metadata:
    name: wordpresssvc
    labels:
        app: wordpress
spec:
    type: ClusterIP
    selector:
        app: wordpress-pod
    ports:
    - name: app-port
      port: 8080
      targetPort: wordpress-port
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: wp-pvc
    labels:
        app: wordpress
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: do-block-storage
---