---
apiVersion: v1
kind: Secret
metadata:
    name: wpdb-cluster-secret
    labels:
        app: wordpress
data:
    ROOT_PASSWORD: bXlwYXNzd29yZA==
---
#create a cluster using CRD
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
    name: wpdb-cluster
    labels:
        app: wordpress

spec:
    replicas: 1
    secretName: wpdb-cluster-secret
    persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
            requests:
                storage: 1Gi
            storageClassName: do-block-storage
